[behave]
# This tells behave to always use the Allure formatter and save results here
format = allure_behave.formatter:AllureFormatter
outfiles = reports/allure-results
stdout_capture = false
stderr_capture = false